version: "3.3"

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "8090:80"
    volumes:
      - "./project:/var/www/html"
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - phalcon
    depends_on:
      - phalcon

  phalcon:    
    build:
      context: ./project
      dockerfile: ../etc/phalcon/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHALCON_VERSION=${PHALCON_VERSION}
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./project:/var/www/html"
      - "./tmp:/tmp"
    links:
      - mongodb

  composer:
    image: "composer"
    volumes:
        - "./project:/var/www/html"
    working_dir: /var/www/html
    command: install --ignore-platform-reqs
    links:
      - phalcon
  web:
    build:
      context: ./project/vue
      dockerfile: ../../etc/web/Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    ports: 
      - "9091:8080"
    volumes:
      - "/app/node_modules" 
      - "./project/vue:/app"

  mongodb:
    image: mongo:${MONGO_VERSION}
    ports:
      - "27027:27017"
    volumes:
      - entrevista2-data:/data/db
      - "./etc/mongodb:/var/www/data"

volumes:
  entrevista2-data:
